--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categorys; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.categorys (
    categorys_id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.categorys OWNER TO estela;

--
-- Name: categorys_categorys_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.categorys ALTER COLUMN categorys_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categorys_categorys_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: categorys_games; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.categorys_games (
    categorys_id bigint NOT NULL,
    game_id bigint NOT NULL
);


ALTER TABLE public.categorys_games OWNER TO estela;

--
-- Name: games; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.games (
    game_id bigint NOT NULL,
    price numeric(10,2),
    name character varying(255),
    characteristics text,
    description text,
    hard_drive_space character varying(255),
    graphics_card character varying(255),
    memory character varying(255),
    operating_system character varying(255),
    processor character varying(255),
    createdAt TIMESTAMP WITHOUT TIME ZONE DEFAULT NOW()
);


ALTER TABLE public.games OWNER TO estela;

--
-- Name: games_game_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.games ALTER COLUMN game_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medias; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.medias (
    id bigint NOT NULL,
    url character varying(255) NOT NULL,
    media_type character varying(50) NOT NULL,
    game_id bigint NOT NULL
);


ALTER TABLE public.medias OWNER TO estela;

--
-- Name: medias_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.medias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sales; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.sales (
    sale_id bigint NOT NULL,
    data_sale timestamp without time zone NOT NULL,
    user_id bigint DEFAULT 9999 NOT NULL
);


ALTER TABLE public.sales OWNER TO estela;

--
-- Name: sales_games; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.sales_games (
    sale_id bigint NOT NULL,
    game_id bigint NOT NULL,
    price numeric(10,2)
);


ALTER TABLE public.sales_games OWNER TO estela;

--
-- Name: sales_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.sales ALTER COLUMN sale_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    administrator boolean DEFAULT false,
    nickname character varying(255) NOT NULL,
    file_name character varying(255) NOT NULL DEFAULT 'default.png'
);


ALTER TABLE public.users OWNER TO estela;

--
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wishlist; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.wishlist (
    user_id bigint NOT NULL,
    game_id bigint NOT NULL
);


ALTER TABLE public.wishlist OWNER TO estela;

--
-- Name: categorys_games categorys_games_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categorys_games
    ADD CONSTRAINT categorys_games_pkey PRIMARY KEY (categorys_id, game_id);


--
-- Name: categorys categorys_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categorys
    ADD CONSTRAINT categorys_pkey PRIMARY KEY (categorys_id);


--
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (game_id);


--
-- Name: medias medias_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.medias
    ADD CONSTRAINT medias_pkey PRIMARY KEY (id);


--
-- Name: sales_games sales_games_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales_games
    ADD CONSTRAINT sales_games_pkey PRIMARY KEY (sale_id, game_id);


--
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (sale_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- Name: wishlist wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (user_id, game_id);


--
-- Name: categorys_games fk_categorys_games_categorys; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categorys_games
    ADD CONSTRAINT fk_categorys_games_categorys FOREIGN KEY (categorys_id) REFERENCES public.categorys(categorys_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- Name: categorys_games fk_categorys_games_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categorys_games
    ADD CONSTRAINT fk_categorys_games_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- Name: medias fk_medias_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.medias
    ADD CONSTRAINT fk_medias_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- Name: sales_games fk_sales_games_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales_games
    ADD CONSTRAINT fk_sales_games_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- Name: sales_games fk_sales_games_sales; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales_games
    ADD CONSTRAINT fk_sales_games_sales FOREIGN KEY (sale_id) REFERENCES public.sales(sale_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- Name: sales fk_sales_users; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk_sales_users FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET DEFAULT NOT VALID;


--
-- Name: wishlist fk_wishlist_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fk_wishlist_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- Name: wishlist fk_wishlist_users; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fk_wishlist_users FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- PostgreSQL database dump complete
--

