--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5
-- Dumped by pg_dump version 17.5

-- Started on 2025-12-26 07:20:42

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 70375)
-- Name: categories; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.categories (
    category_id bigint NOT NULL,
    name character varying(255)
);


ALTER TABLE public.categories OWNER TO estela;

--
-- TOC entry 225 (class 1259 OID 70374)
-- Name: categories_category_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.categories ALTER COLUMN category_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 70393)
-- Name: categories_games; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.categories_games (
    category_id bigint NOT NULL,
    game_id bigint NOT NULL
);


ALTER TABLE public.categories_games OWNER TO estela;

--
-- TOC entry 217 (class 1259 OID 62053)
-- Name: games; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.games (
    game_id bigint NOT NULL,
    price numeric(10,2),
    name character varying(255),
    characteristics text,
    description text,
    hard_drive_space character varying(255),
    graphics_card character varying(255),
    memory character varying(255),
    operating_system character varying(255),
    processor character varying(255),
    createdat timestamp without time zone DEFAULT now()
);


ALTER TABLE public.games OWNER TO estela;

--
-- TOC entry 218 (class 1259 OID 62058)
-- Name: games_game_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.games ALTER COLUMN game_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.games_game_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 70419)
-- Name: media; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.media (
    media_id bigint NOT NULL,
    url character varying(255) NOT NULL,
    media_type character varying(50) NOT NULL,
    game_id bigint NOT NULL
);


ALTER TABLE public.media OWNER TO estela;

--
-- TOC entry 228 (class 1259 OID 70418)
-- Name: media_media_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.media ALTER COLUMN media_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 62063)
-- Name: sales; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.sales (
    sale_id bigint NOT NULL,
    data_sale timestamp without time zone NOT NULL,
    user_id bigint DEFAULT 9999 NOT NULL
);


ALTER TABLE public.sales OWNER TO estela;

--
-- TOC entry 220 (class 1259 OID 62067)
-- Name: sales_games; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.sales_games (
    sale_id bigint NOT NULL,
    game_id bigint NOT NULL,
    price numeric(10,2)
);


ALTER TABLE public.sales_games OWNER TO estela;

--
-- TOC entry 221 (class 1259 OID 62070)
-- Name: sales_sale_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.sales ALTER COLUMN sale_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_sale_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 62071)
-- Name: users; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    administrator boolean DEFAULT false,
    nickname character varying(255) NOT NULL,
    file_name character varying(255) DEFAULT 'default.png'::character varying
);


ALTER TABLE public.users OWNER TO estela;

--
-- TOC entry 223 (class 1259 OID 62077)
-- Name: users_user_id_seq; Type: SEQUENCE; Schema: public; Owner: estela
--

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 62078)
-- Name: wishlist; Type: TABLE; Schema: public; Owner: estela
--

CREATE TABLE public.wishlist (
    user_id bigint NOT NULL,
    game_id bigint NOT NULL
);


ALTER TABLE public.wishlist OWNER TO estela;

--
-- TOC entry 4793 (class 2606 OID 70397)
-- Name: categories_games categories_games_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categories_games
    ADD CONSTRAINT categories_games_pkey PRIMARY KEY (game_id, category_id);


--
-- TOC entry 4791 (class 2606 OID 70379)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (category_id);


--
-- TOC entry 4779 (class 2606 OID 62086)
-- Name: games games_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.games
    ADD CONSTRAINT games_pkey PRIMARY KEY (game_id);


--
-- TOC entry 4795 (class 2606 OID 70423)
-- Name: media media_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT media_pkey PRIMARY KEY (media_id);


--
-- TOC entry 4783 (class 2606 OID 62090)
-- Name: sales_games sales_games_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales_games
    ADD CONSTRAINT sales_games_pkey PRIMARY KEY (sale_id, game_id);


--
-- TOC entry 4781 (class 2606 OID 62092)
-- Name: sales sales_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT sales_pkey PRIMARY KEY (sale_id);


--
-- TOC entry 4785 (class 2606 OID 62094)
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- TOC entry 4787 (class 2606 OID 62096)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);


--
-- TOC entry 4789 (class 2606 OID 62098)
-- Name: wishlist wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT wishlist_pkey PRIMARY KEY (user_id, game_id);


--
-- TOC entry 4801 (class 2606 OID 70398)
-- Name: categories_games fk_categories_games_categorys; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categories_games
    ADD CONSTRAINT fk_categories_games_categorys FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON DELETE CASCADE;


--
-- TOC entry 4802 (class 2606 OID 70403)
-- Name: categories_games fk_categories_games_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.categories_games
    ADD CONSTRAINT fk_categories_games_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON DELETE CASCADE;


--
-- TOC entry 4803 (class 2606 OID 70424)
-- Name: media fk_media_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.media
    ADD CONSTRAINT fk_media_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON DELETE CASCADE;


--
-- TOC entry 4797 (class 2606 OID 62114)
-- Name: sales_games fk_sales_games_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales_games
    ADD CONSTRAINT fk_sales_games_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4798 (class 2606 OID 62119)
-- Name: sales_games fk_sales_games_sales; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales_games
    ADD CONSTRAINT fk_sales_games_sales FOREIGN KEY (sale_id) REFERENCES public.sales(sale_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4796 (class 2606 OID 62124)
-- Name: sales fk_sales_users; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.sales
    ADD CONSTRAINT fk_sales_users FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE SET DEFAULT NOT VALID;


--
-- TOC entry 4799 (class 2606 OID 62129)
-- Name: wishlist fk_wishlist_games; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fk_wishlist_games FOREIGN KEY (game_id) REFERENCES public.games(game_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


--
-- TOC entry 4800 (class 2606 OID 62134)
-- Name: wishlist fk_wishlist_users; Type: FK CONSTRAINT; Schema: public; Owner: estela
--

ALTER TABLE ONLY public.wishlist
    ADD CONSTRAINT fk_wishlist_users FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON UPDATE CASCADE ON DELETE CASCADE NOT VALID;


-- Completed on 2025-12-26 07:20:43

--
-- PostgreSQL database dump complete
--

